
## 研究角度
1. 经济不确定性对不同板块的影响以及时期差异性(wind资讯可以获得一级行业指数，比如医疗保健)
   - 选择哪几个板块
2. 疫情期间，医疗保健行业板块和整个股市的溢出效应
3. 对于其他的类似于具有股市特征的债市、汇市以及期货等金融资本市场来说，引进
   GARCH-MIDAS模型的进行研究同样是极具研究意义的课题。
   - 宏观经济与其他金融资本市场
   - GARCH-MIDAS模型的应用在哪些方面
## 总结
关于股市的研究有两类，一类是金融市场不同金融产品(eg.股债两市)相关性的研究，一类
是宏观经济对金融子市场的影响研究

## 文献整理

### 指标构建类
[1]李家琦.一个基于主成分分析的探测高维变点的方法[J/OL].数理统计与管理
:1-12[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200223-001.

[2]俞立平,钟昌标.创新政策、研发补贴对企业研发投入的影响研究——机理、大小、规律
[J/OL].数理统计与管理
:1-13[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200123-007.

[3]李旭辉,彭勃,程刚.长江经济带人工智能产业发展动态评价及系统协调度研究[J].统计与
信息论坛,2020,35(01):89-100.
1. 创新点:人工智能产业发展
2. 方法:指标体系构建(用乘法集成法将熵权法和主观赋权进行组合)
3. 难点:数据收集


### 统计方法应用
[1]陈秋华,杨慧荣,崔恒建.变量筛选后的个人信贷评分模型与统计学习[J/OL].数理统计与
管理:1-13[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200223-002.
[2]王心语,黄在鑫.基于SGT分布的ES估计、后验分析及在沪深股市中应用[J/OL].数理统计
与管理:1-15[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200123-005.
1. 创新点:基于SGT分布的EGARCH模型来估计ES的研究成果;使用Du和Escanciano提出的条件
          和无条件后验分析方法分别对该模型的稳健性进行检验。
2. SGT分布拥有三个控制参数：偏度参数、峰度参数及尾部厚度参数。

[3]宋玉平,陈志兰.基于连续混合正态分布的期货定价偏差研究[J].统计与信息论
坛,2020,35(01):23-29.
1. 内容:利用连续混合正态分布模型对期货理论价格和实际价格之间偏差的分布进行拟合
2. 方法:先采用基于牛顿迭代的极大似然估计法对未知参数进行估计,再进一步利用模拟退
   火算法对牛顿迭代的结果进行优化

[4]唐晓彬,董曼茹,乔天立,张瑞.中国资本市场资产价格波动的动态关联性检验[J].统计与
信息论坛,2020,35(01):53-63.
1. 创新点:将黄金市场、石油市场、股票市场和债券市场纳入统一框架,并采用Markov区制
   转换模型进行探讨.
2. 内容:在理清四种市场波动率转换及波动率状态持续机理的基础上,充分考虑四种市场之
   间的动态关联性特征及金融风险关联性.
3. 模型:Ｍarkov三区制状态转移模型与动态相关系数DCC模型

[5]夏婷,闻岳春.经济不确定性是股市波动的因子吗?——基于GARCH-MIDAS模型的分析[J].中
国管理科学,2018,26(12):1-11.
1. 经济不确定有两方面:宏观经济不确定性包括实体经济运行情况、消费情况、货币政策，
   经济政策不确定性用EPU指标
2. 将外生变量引入多元混频模型，分析短期波动率和长期波动率。
3. 研究对象为A股和B股

[6]STOCK MARKET VOLATILITY AND MACROECONOMIC FUNDAMENTALS
   说明:[8]的英文参考文献

[7]沪铜期货与上证A股长短期波动与动态非对称相关性研究——基于宏观经济因素视角的混
频数据分析
1. 利用GARCH-MIDAS模型研究宏观经济波动如何影响股票价格和金属商品资产价格波动
2. 根据上面模型的残差建立DCC-MIDAS动态模型，根据不同历史事件划分样本区间, 考察期
   货市场和股票市场长期相关性的结构性变化(金融危机前后)。

[8]金融危机和地产调控冲击下地产板块和整体股市的波动性研究
1. 模型:采用BEKK-GJR-GARCH模型
2. 考察了地产板块和整体股市之间的均值溢出和波动溢出效应
3. 内容:
   - 用含有非对称因素的VAR研究两个指标整体的的均值溢出效应
   - 用含有虚拟变量的BEEK-GJR-GARCH研究两个指标整体的的波动溢出效应(虚拟变量为两
     次危机和六次地产调控)
   - 在2018年和2015年两个特定窗口研究两个指标之间的溢出效应
4. 指标:整体股市用上证综指，地产板块用上证地产指数
5. idea:疫情期间，医疗保健行业板块和整个股市的溢出效应。
   
[9]中国股市行业板块极端风险测度及溢出效应研究
[10]中国不同类型经济政策不确定性的宏观经济效应对比研究
   说明:有适合中国的经济政策不确定性指标
   （https://economicpolicyuncertaintyinchina.weebly.com/）

[11]基于GARCH-MIDAS模型的宏观经济与股市波动关系
1. 内容:建立多因子GARCH-MIDAS模型研究宏观经济与股票市场波动关系
2. 细节处理:
   - 将宏观经济变量拟合ARMA模型后的残差序列作为宏观经济的波动性度量
   - 将样本区间划分为三个阶段
3. 指标:
   - 股市:上证综指日收益率
   - 宏观指标:工业增加值（IP）、利率（R）（银行间30日拆借利率）、通货膨胀率(CPI)、货币供应量(M2)以及社会消费品零售总额(SAles);
   - 宏观指标均采用同比指标，因此不需要进行季节调整
   - 宏观指标的多重共线性检验(计算指标的相关系数和方差膨胀因子VIF以及容忍度)

[12]经济政策不确定性如何影响金融市场间的流动性协同运动?——基于中国金融周期的视角
1. 股债两市流动性的相关性(经济政策不确定性如何影响股债两市流动性自身的波动及市场
   间的联动,进一步考察这一影响在金融周期的不同阶段是否呈现非对称性)。
2. 模型:DCC-MIDAS，流动性测度
3. 创新点:
   - 现有对金融市场动态相关性的研究普遍集中于收益及其波动，作者从市场流动性联动的视角出发
   - 对DCC-GARCH-MIDAS模型引入经济不确定性和经济周期虚拟变量

[13]银行间债券市场与利率互换市场的联动性——基于DCC-MIDAS模型的实证
1. 大多数研究学者认为金融市场的波动一部分来源于宏观经济波动，还有一部分来源于随
   机的突发事件、日内交易及投资者情绪等，根据金融市场波动率的产生根源，可以将金
   融市场的波动进行成分分解。应用DCC-MIDAS模型，从长短期两个角度考察中国银行间债
   券市场与利率互换市场之间的联动性及宏观经济风险对两个市场波动性的影响。
2. 创新点：
   - 在DCC-MIDAS中引入宏观经济风险
   - 研究对象的创新:银行间债券市场与利率互换市场，大部分研究是关注股市.
3. 模型：DCC-MIDAS模型是DCC模型和GARCH-MIDAS模型的有机结合，不仅能够刻画每个市场
   的混频成分波动，还能分析多个市场间的波动率成分动态条件相关。
4. 对象:
   - 债券:银行间债券市场总指数的财富指数
5. 变量：宏观经济变量季节性处理后的残差序列平方作为波动率来度量经济波动性。

[14]Can economic policy uncertainty predict exchange rate volatility? New
evidence from the GARCH-MIDAS model
1. 研究对象:中美经济政策的不确定性对汇率波动性的影响
2. 模型:GARCH-MIDAS与传统的GARCH类模型进行对比
3. 创新:研究对象的选择有新意