gantt

    title 论文写作计划及措施
    dateFormat  YYYY-MM-DD

    section 准备阶段
    阅读文献                  :done,a1, 2020-02-01,45d
    讨论研究方向,拟定题目      :done,a2, 2020-03-15,30d
    写开题报告,在导师指导下修改 :active,a3, 2020-04-15,45d

    开题答辩,根据答辩老师建议修改论文框架    :crit,a4, 2020-06-10,30d
    section 撰写阶段
    理解论文所用模型及理论    :a4,2020-06-10 , 60d
    撰写论文初稿             :a6,2020-08-01 , 90d

    section 答辩阶段
    预答辩      :crit,2020-11-01  , 30d
    根据答辩老师的建议修改论文完成二稿:2020-12-01  , 90d
    论文查重并修改: 2021-03-01 , 30d
    论文盲审并进一步修改论文完成终稿: 2021-04-01 , 30d
    论文答辩: crit,2021-05-01  , 30d

