---
title: "文献整理"
author: "WHH"
date: "2020年3月"
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2005-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
nocite: '@*'
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---

题目:**经济政策不确定性与我国股市收益率及波动率的关系研究**

**经济政策不确定性对股票市场的影响研究**

# 大纲

1. **导论**
   - 一、研究背景及意义
      - 研究背景
      - 研究意义

   - 二、国内外文献综述
        
      - 经济政策不确定性文献综述
      - 经济政策不确定性对股票市场影响的文献综述
      - MIDAS模型应用文献综述

   - 三、研究方法及内容框架
      - 研究方法
      - 研究内容
      - 研究思路(画图)

   - 四、论文拟创新之处
      - 使用基于t分布的GARCH-MIDAS

2. 第一章 经济政策不确定性指标和混频模型简介
   - 第一节 经济政策不确定性指标定义及测度

    * 采用香港大学黄昀的经济政策不确定性指数

   - 第二节 经济政策不确定性对股市的影响机制
     - 一、财政政策对股票市场的影响
     - 二、货币政策对股票市场的影响
     - 三、汇率政策对股票市场的影响

   - 第三节 基于混频数据的MIDAS模型和GARCH-MIDAS模型介绍
     - 一、混合数据采样回归模型(MIDAS)理论基础
     - 二、广义自回归条件异方差混频数据抽样模型(GARCH-MIDAS)理论基础
     - 三、模型信度集合检验(model confidence set,MCS检验)方法

3. 第二章 经济政策不确定性对上证综指收益率的影响研究
   - 第一节 数据选取和描述性统计
     - 一、数据选取和预处理   
       - 股市数据怎么选
       - 自变量选那几个国家的EPU
       - 涉及到的宏观经济变量有哪些，波动率研究是否要包含宏观经济变量
       - 数据时间段是哪里
       - 数据处理:宏观变量的处理（取对数做差分等）

     - 二、股市收益率序列的描述性分析及检验
       - 基本统计量计算
       - 序列图
       - 上证综指收益率序列基本检验(平稳性检验、正态性检验以及ARCH效应检验)
       - 自相关和偏相关检验

   - 第二节 基于MIDAS模型的经济政策不确定性对沪深300指数收益率影响研究
     - 一、基于MIDAS模型的沪深300指数收益率模型构建
     - 二、沪深300指数收益率模型比较及最优模型选择
       * 滞后阶数和权重系数的选择，包含不同宏观经济变量的模型比较
   
     - 三、模型结果解释

   - 第三节 基于MIDAS模型的不同类型经济政策不确定性对沪深300指数收益率影响研究
     - 一、财政政策不确定性对沪深300指数收益率影响的MIDAS模型构建
     - 二、货币政策不确定性对沪深300指数收益率影响的MIDAS模型构建
     - 三、汇率政策不确定性对沪深300指数收益率影响的MIDAS模型构建
     - 四、不同类型经济政策不确定性对沪深300指数收益率影响的对比分析


4. 第三章 经济政策不确定性对沪深300指数波动率的影响研究

   - 第一节 基于GARCH-MIDAS模型的经济政策不确定性对沪深300指数波动率影响研究
     - 一、经济政策不确定性对沪深300指数波动率影响的GARCH-MIDAS-norm模型构建    
     - 二、经济政策不确定性对沪深300指数波动率影响的GARCH-MIDAS-t模型构建
     - 三、沪深300指数波动率最优GARCH-MIDAS模型选择
     - 四、模型参数估计和解释
  
       - 涉及长短期波动率时序图分析；
       - 对波动率的贡献度分析
       - 是否存在阶段性特征(注意结合重大金融事件的发生)，与经济政策不确定性指数的趋势有什么关系；
       - 权重系数分析,下一节的非对称效应分析；
       - 二者之间是正相关还是负相关

   - 第二节 基于含有非对称效应的GJR-GARCH-MIDAS模型的经济政策不确定性对沪深300指数波动率影响研究
     - 一、经济政策不确定性对股市波动率影响的GJR-GARCH-MIDAS-norm模型构建
     - 二、经济政策不确定性对沪深300指数波动率影响的GJR-GARCH-MIDAS-t模型构建
     - 三、沪深300指数波动率最优GJR-GARCH-MIDAS模型选择
     - 四、模型参数估计与解释

   - 第三节 沪深300指数的波动率预测
     - 一、沪深300指数的波动率的短期(长期)预测
     - 二、损失函数及模型信度集合检验(model confidence set,MCS检验)


5. **结论与展望**
   - 结论
   - 不足与展望
     - 可以研究经济政策不确定性对多国股市动态相关性的影响
  
6. **参考文献**

第一次出现要写出中文

# 问题

既然是研究经济政策不确定性对股市的影响，那考虑经济政策不确定性对股市是如何影响
的，影响呈现什么样的特征，比如不同阶段的影响大小，影响方向，是建立在经济政策不确
定性对股市是有影响的基础上。
如何区分外文文献

# 研究角度

1. 经济不确定性对不同板块的影响以及时期差异性(wind资讯可以获得一级行业指数，比如医疗保健)
   - 选择哪几个板块
2. 疫情期间，医疗保健行业板块和整个股市的溢出效应
3. 对于其他的类似于具有股市特征的债市、汇市以及期货等金融资本市场来说，引进
   GARCH-MIDAS模型的进行研究同样是极具研究意义的课题。
   - 宏观经济与其他金融资本市场(债券)
   - GARCH-MIDAS模型的应用在哪些方面
  
# 文献总结整理

1. 关于EPU的研究有宏观微观的，
2. 关于GARCH-MIDAS在金融市场的应用，设计不同模型对比，大致分为三类:
   * 一类是宏观经济变量对金融市场某个指标(如标普500，上证综指，沪深300，债券，银
     行同业拆借率)的影响研究,
   * 一类是经济政策不确定性和宏观经济的结合对金融市场(原油，黄金，股市)的影响研究
   * 一类是经济政策不确定性对金融市场(股市，汇率)的单独影响研究

3. 利用DCC-MIDAS做宏观层面对金融对象动态关系的影响研究

# 文献整理

## 统计方法应用
[1]陈秋华,杨慧荣,崔恒建.变量筛选后的个人信贷评分模型与统计学习[J/OL].数理统计与
管理:1-13[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200223-002[@陈秋华2020].

[2]王心语,黄在鑫.基于SGT分布的ES估计、后验分析及在沪深股市中应用[J/OL].数理统计
与管理:1-15[2020-03-20].https://doi.org/10.13860/j.cnki.sltj.20200123-005[@王心语2020].

1. 创新点:基于SGT分布的EGARCH模型来估计ES的研究成果;使用Du和Escanciano提出的条件
          和无条件后验分析方法分别对该模型的稳健性进行检验。
2. SGT分布拥有三个控制参数：偏度参数、峰度参数及尾部厚度参数。

[3]宋玉平,陈志兰.基于连续混合正态分布的期货定价偏差研究[J].统计与信息论
坛,2020,35(01):23-29[@宋玉平2020].

1. 内容:利用连续混合正态分布模型对期货理论价格和实际价格之间偏差的分布进行拟合
2. 方法:先采用基于牛顿迭代的极大似然估计法对未知参数进行估计,再进一步利用模拟退
   火算法对牛顿迭代的结果进行优化

[4]唐晓彬,董曼茹,乔天立,张瑞.中国资本市场资产价格波动的动态关联性检验[J].统计与
信息论坛,2020,35(01):53-63[@唐晓彬2020].

1. 创新点:将黄金市场、石油市场、股票市场和债券市场纳入统一框架,并采用Markov区制
   转换模型进行探讨.
2. 内容:在理清四种市场波动率转换及波动率状态持续机理的基础上,充分考虑四种市场之
   间的动态关联性特征及金融风险关联性.
3. 模型:Ｍarkov三区制状态转移模型与动态相关系数DCC模型

[5]夏婷,闻岳春.**经济不确定性是股市波动的因子吗?——基于GARCH-MIDAS模型的分析**[J].中
国管理科学,2018,26(12):1-11[@夏婷2018].

1. 经济不确定有两方面:宏观经济不确定性包括实体经济运行情况、消费情况、货币政策，
   经济政策不确定性用EPU指标
2. 将外生变量引入多元混频模型，分析短期波动率和长期波动率。
3. 研究对象为A股和B股

[6]STOCK MARKET VOLATILITY AND MACROECONOMIC FUNDAMENTALS   The Review of
Economics and Statistics   2013-07[@Engle2013].
   说明:[8]的英文参考文献

[8]金融危机和地产调控冲击下地产板块和整体股市的波动性研究[J].统计研究,2019,36(02):38-49[@袁圆2019].

1. 模型:采用BEKK-GJR-GARCH模型
2. 考察了地产板块和整体股市之间的均值溢出和波动溢出效应
3. 内容:
   - 用含有非对称因素的VAR研究两个指标整体的的均值溢出效应
   - 用含有虚拟变量的BEEK-GJR-GARCH研究两个指标整体的的波动溢出效应(虚拟变量为两
     次危机和六次地产调控)
   - 在2018年和2015年两个特定窗口研究两个指标之间的溢出效应
4. 指标:整体股市用上证综指，地产板块用上证地产指数
5. idea:疫情期间，医疗保健行业板块和整个股市的溢出效应。
   
[9]中国股市行业板块极端风险测度及溢出效应研究[D].华中科技大学,2019.

[10]中国不同类型经济政策不确定性的宏观经济效应对比研究[J/OL].当代经济科学
   :1-21[2020-03-23].http://kns.cnki.net/kcms/detail/61.1400.F.20200218.1049.002.html[@金春雨2020].
   
   说明:有适合中国的经济政策不确定性指标，从2000年1月1日开始
   （https://economicpolicyuncertaintyinchina.weebly.com/）

[11]基于GARCH-MIDAS模型的宏观经济与股市波动关系[J].计算机工程与应用,2019,55(15):257-262+270[@石强2019].

1. 内容:建立多因子GARCH-MIDAS模型研究宏观经济与股票市场波动关系
2. 细节处理:
   - 将宏观经济变量拟合ARMA模型后的残差序列作为宏观经济的波动性度量
   - 将样本区间划分为三个阶段
3. 指标:
   - 股市:上证综指日收益率
   - 宏观指标:工业增加值（IP）、利率（R）（银行间30日拆借利率）、通货膨胀率(CPI)、货币供应量(M2)以及社会消费品零售总额(SAles);
   - 宏观指标均采用同比指标，因此不需要进行季节调整
   - 宏观指标的多重共线性检验(计算指标的相关系数和方差膨胀因子VIF以及容忍度)

[12]经济政策不确定性如何影响金融市场间的流动性协同运动?——基于中国金融周期的视角[J].统计研究,2020,37(02):37-51[@张宗新2020].

1. 股债两市流动性的相关性(经济政策不确定性如何影响股债两市流动性自身的波动及市场
   间的联动,进一步考察这一影响在金融周期的不同阶段是否呈现非对称性)。
2. 模型:DCC-MIDAS，流动性测度
3. 创新点:
   - 现有对金融市场动态相关性的研究普遍集中于收益及其波动，作者从市场流动性联动的视角出发
   - 对DCC-GARCH-MIDAS模型引入经济不确定性和经济周期虚拟变量
4. 摘要:金融市场间流动性出现高协同运动是发生危机传染的重要表现之一,因此,针对流动
   性动态联动效应的研究显得极为重要。本文基于中国金融市场数据测算了2003-2018年间
   我国股市、债市流动性,并对Colacito等(2011)的混频数据抽样动态条件相关系数模型
   (DCC-MIDAS)进行了扩展,同时从金融周期视角出发,运用扩展后的模型考察了经济不确定
   性在不同时间区间内对于流动性波动率和相关性是否存在不同的作用效果。研究结果表
   明,相较于单因子混频模型,引入经济政策不确定性的多因子混频模型可以更好地捕捉我
   国股债两市相关性的动态变化;同时,经济政策不确定性的提高会降低股债两市流动性的
   正相关性,但这一作用效果会在金融周期的拐点处转为加强两者的正相关性。本文不仅为
   讨论股债两市联动效应提供了流动性的新视角,也为金融市场风险监管提供了重要的参考
   依据。
   
[13]银行间债券市场与利率互换市场的联动性——基于DCC-MIDAS模型的实证[J].系
   统工程,2018,36(01):13-21[@张屹山2018].

1. 大多数研究学者认为金融市场的波动一部分来源于宏观经济波动，还有一部分来源于随
   机的突发事件、日内交易及投资者情绪等，根据金融市场波动率的产生根源，可以将金
   融市场的波动进行成分分解。应用DCC-MIDAS模型，从长短期两个角度考察中国银行间债
   券市场与利率互换市场之间的联动性及宏观经济风险对两个市场波动性的影响。
2. 创新点：
   - 在DCC-MIDAS中引入宏观经济风险
   - 研究对象的创新:银行间债券市场与利率互换市场，大部分研究是关注股市.
3. 模型：DCC-MIDAS模型是DCC模型和GARCH-MIDAS模型的有机结合，不仅能够刻画每个市场
   的混频成分波动，还能分析多个市场间的波动率成分动态条件相关。
4. 对象:
   - 债券:银行间债券市场总指数的财富指数
5. 变量：宏观经济变量季节性处理后的残差序列平方作为波动率来度量经济波动性。

[14]Can economic policy uncertainty predict exchange rate volatility? New
evidence from the GARCH-MIDAS model[J]. Finance Research Letters,2019[@Zhou2019].

1. 研究对象:中美经济政策的不确定性对汇率波动性的影响
2. 模型:GARCH-MIDAS与传统的GARCH类模型进行对比
3. 内容:the Sino-US EPU ratio对中国汇率波动率的影响以及the Sino-US EPU ratio如何预测汇率的波动性。
4. 细节:汇率从2005年开始发行，2016年，RMB加入SDR,成为继美元欧元之后占比第三的货
   币。汇率波动会影响对外贸易成本，增加国内外投资风险。
5. 创新:研究对象的选择有新意
6. 指标:
   - 汇率(2003-01-01到2018-09-28的日度数据)
   - 中美经济不确定性:the Sino-US EPU ratio(2003-01到2018-09的月度数据)=中国EPU/美国EPU

## 经济不确定性

### 经济政策不确定性与贸易
[1]经济政策不确定性对亚太地区进口贸易的影响 亚太经济[@杨旭2020]

1. 数据说明:
   经济不确定性用(Baker2016)基于新闻报纸提出的EPU[@BAKER2016].然后求年平均值。
2. 梳理经济政策不确定性对进口贸易的影响机制，经济不确定性是如何影响进口贸易的,首
   先提出经济假设:
   - 影响国内供给
   - 影响国外供给
   - 影响国内需求
3. 对进口贸易从质和量两个方面进行分析，以进口技术复杂度进行衡量。

### 微观:经济不确定性与企业的投资行为

[2]经济政策不确定性、财务柔性与企业研发投资的关系研究 中国物价[@张依婷2020]

从微观角度出发，利用Baker等构造的中国经济政策不确定性指数,从多个角度探讨中国经济
政策不确定下财务柔性与企业研发投资的关系（微观企业行为）。

[3]从供需角度看经济政策不确定性对房价的影响——基于我国40个大中城市面板数据的实证
研究 中国物价[@张晓颖2020]

1. 数据说明:经济不确定性用(Baker2016)基于新闻报纸提出的EPU[@BAKER2016].然后求年平均值。
2. 分析经济政策不确定性对不同类型城市房价的影响及机理，从需求和供给方面研究经济政策
不确定性对房价的影响

[4]经济政策不确定性对企业技术创新的影响[@余青如2020]

1. 创新活动有投入和产出两方面
2. 研发费用占主营收入之比衡量创新投入。选用发明专利申请数（Patent）作为创新产出
   的代理变量，并将其加1取自然对数。
3. 经济政策不确定性（EPU）。采用Baker等（2016）构建的月度经济政策不确定性指数，
   并用算术平均法将其转化为年度变量。
4. 选取了2009～2016年中国所有创业板上市公司为研究样本

### 经济政策不确定性与外商直接投资、就业率等宏观经济

[1]经济政策不确定性对FDI影响研究 经济问题[@单东方2020]

1. FDI:外商直接投资 
2. 经济不确定性指标由三部分构成:
   - 第一部分是汇集量化各大类报纸中经济政策不确定性的相关消息报道;
   - 第二部分是未来即将到期的税法规定;
   - 第三部分是与货币政策和政府支出有关的不确定部分。
   - 经济政策不确定指数分别对上述三个成分采用1/2、1/6和1/3
3. 利用VAR模型进行区域差异分析，东中西地区EPU对FDI的影响程度不同。
4. 除了外商直接投资，还有企业对外投资，引进投资等角度

[2]经济政策不确定性对就业率的影响研究——来自21个经济体的经验证据[@谢廷宇2020]

1. 经济不确定性与就业:
   
本文所选择样本是澳大利亚、巴西、加拿大、智利、中国、哥伦比
亚、法国、德国、希腊、印度、意大利、冰岛、日本、瑞士、俄罗斯、新加坡、墨西哥、西
班牙、美国、韩国和英国等21个国家。该样本既有发达国家、发展中国家和新兴经济体，又
有遭受重大经济政治冲击的国家。以21个经济体为研究对象，分析了经济政策不确定性对国
家就业率的影响.

算术平均法或加权平均法得到年度经济政策不确定指数。

2. Baker的EPU指数

[3]全球经济政策不确定性对跨境资金流动的影响——来自67个经济体的经验证据[@李姣姣2020]

Baker等的全球经济政策不确定性指数和FDI

[4]经济政策不确定性对经济波动的动态影响[@孙永强2018]

1. 采用MVEGARCH模型，对中国等多个国家经济政策不确定性与经济波动之间的影响机制
进行了实证分析.以通货膨胀和产出来衡量经济波动,采用居民消费价格指数(CPI)反映通货
膨胀状况，而以实际工业增加值(IPI)反映产出状况。

均是月度数据

2. 经济不确定性用2013年Bake和Bloom构造的EPU指数
   Baker，S． B． ，Bloom，N． ，2013． “Does Uncertainty Ｒeduce Growth?”NBEＲ
   Working Paper． No． 19475．

### 我国经济政策不确定指数对不同股市的影响

[1]经济政策不确定性与我国股市的波动率预测[@余江2018]

1. 我国经济政策不确定性对沪深300指数波动率的预测作用.

[6]中国经济政策不确定性与亚洲股市的动态关系——基于时变Copula模型的分析[@韩菲2018]

1. 发现一国的经济政策不确定性不仅会对本国的股票价格产生影响, 同样会对其他国家的
   经济政策不确定性或宏观经济产生溢出, 这种跨国别的经济政策不确定性溢出势必会进
   一步影响该国的股市
2. 选取上证综指 (SHZ) 、泰国综指 (SETI) 、印度孟买SENSEX30指数 (SENSEX) 、马来西
   亚吉隆坡综指 (KLSE) 、日经225指数 (N225) 、韩国综合指数 (KS11) 、香港恒生指数
   (HSI) 、新加坡海峡时报指数 (STI) 分别代表中国内地、泰国、印度、马来西亚、日
   本、韩国、香港和新加坡的股票市场价格, 选取其**月度数据**为原始样本
3. 选取Baker et al. (2016) 构建的中国经济政策不确定性指数 (EPU) 作为中国经济政策
   不确定性的代理变量


### 外国文献

#### EPU与FDI

[1]Determinants of foreign direct investment inflows: The role of economic
policy uncertainty[@Canh2020]

1. 外国直接投资流入的决定因素：经济政策不确定性的作用

2. 摘要：2003-2013年间21个经济体的国内经济政策不确定性（EPU）和世界不确定性（WUI）对净外
国直接投资流入（FDI）的影响。通过使用线性面板数据模型的顺序（两阶段）技术，本研
究提供了两个主要结果。首先，国内EPU的增长率对外国直接投资流入产生不利影响。其
次，结合国内EPU水平，包括143个国家的经济政策不确定性指标的世界不确定性（WUI）对
流入东道国的FDI产生积极影响。调查结果表明，尽管国内经济政策的不确定性对外国直接
投资的流入有不利影响；全球（世界）经济政策不确定性的增加可能会增加流入该国的外国
直接投资。我们通过行为偏差（锚定和调整）的存在来解释这种对全球不确定性的系统厌
恶，从而说明投资者对其将框架与不确定性相关联的能力的敏感性。

3. 自己的EPU对FDI的影响；世界的EPU对FDI的影响

[2]Tail dependence structures between economic policy uncertainty and foreign
exchange markets: Nonparametric quantiles methods[@Al-Yahyaee2020]

本研究考察了澳大利亚，加拿大，中国，欧盟，日本，墨西哥，英国和美国的经济政策不确
定性（EPU）与主要实际外汇市场（FER）之间的极端依赖关系和非线性因果关系。我们还探
讨了财务不确定性（FU）-FER关系。为此，我们使用了分位数上的分位数（QQ）方法和分位
数上的非参数因果关系检验。使用QQ方法，结果显示EPU和FER之间的负平均值和极端依赖
性。此外，发现所考虑变量之间的依存关系结构在整个分位数上是不对称的。通过应用非参
数分位数因果关系检验，我们从本地和美国金融机构中发现了均值因果关系的弱证据（在中
等分位数处），并且有力证据表明了均方因果关系（几乎所有分位数）。 EPU到FER。最
后，在我们对2008-2009年全球金融危机（GFC）进行分析期间，EPU与FER之间的联系得到了
加强。这些结果对货币交易者和货币政策具有重要意义。

#### EPU与微观层面的关系研究

[1]Navigating through economic policy uncertainty: The role of corporate cash
holdings[@Duong2020]

微观方面（应对经济政策的不确定性：公司现金持有量的作用）

[2]A study on the relationship between economic policy uncertainty and overseas travel expenditure[@김도경2020]

经济政策不确定性与海外旅行支出之间的关系研究,本研究着眼于来源国内部环境对海外旅
行支出的影响

## EPU+GARCH-MIDAS+金融市场

### 外文文献

#### GEPU与黄金

1. The importance of global economic policy uncertainty in predicting gold
   futures market volatility: A GARCH‐MIDAS approach[@Fang2018].

   - 由于黄金的获利性和风险规避性质，经济政策不确定性会影响黄金价格，从而导致波动

   数百年来，古老的黄金一直是重要的贵重金属，它在价值储存中起着特殊的作用，尤其
   是在政治和经济动荡时期（Aggarwal＆Lucey，2007）。作为用于交易和货币对冲的全球
   货币储备的重要组成部分（Capie，Mills和Wood，2005年），与大型商品市场中的其他
   金属相比，黄金具有明显的优势和突出的地位。由于获利情况和显着的风险规避特征，
   黄金市场已经积极地经历了这种情况。媒体报道和投资建议经常强调，在经济和政治动
   荡时期，黄金行为是经典的避险和对冲投资。但是，从2007年到2009年，名义金价已上
   涨了42％。在危机时期，金价的变化很大程度上受到经济不确定性的影响（Bams，
   Blanchard，Honarvar和Lehnert，2017；Białkowski，Bohl，Stephan和Wisniewski，
   2014）。例如，中央银行黄金储备的增加，加上对黄金市场的投机活动，促使金价创下
   历史新高。因此，一项关于预测黄金波动性及其背后因素的研究引起了选择购买黄金的
   投资者和决策者的兴趣（Cai，Cheung，＆Wong，2001; Khalifa，Miao，
   ＆Ramchander，2011; Uludag＆Lkhamazhapov，2014; Zhang ＆魏,2010)

   然而，关于黄金波动如何对经济和政治不确定性做出反应的文献很少。本质上，较高的
   经济政策不确定性（EPU）反映了动荡的宏观经济政策环境，这削弱了投资者的信心，并
   进一步导致了股市同步下跌。例如，阿方索和索萨（Afonso and Sousa，2012年）表
   明，财政政策变化中的政府支出冲击对国内生产总值（GDP）的影响很小，从而导致重要
   的“挤出效应”。因此，它们对房价产生了不同的影响，并导致股票价格立即下跌。
   Pastor和Veronesi（2012）建议，在政策变化公告中，股票市场的回报平均应为负数。
   政策的变化应使股票收益波动更大，各公司之间的相关性更高。因此，人们可能转向避
   险天堂，例如黄金，这导致了金价的上涨。考虑到黄金市场的波动性是高度持续的
   （Cochran，Mansur，＆Odusami，2012; Hammoudeh＆Yuan，2008; Yaya，Tumala，
   ＆Udomboso，2016），意外的冲击或新闻导致当前的黄金波动性更高，从而增加了未来
   的波动性。因此，我们将调查GEPU是否会对黄金市场的波动产生影响.
   
   - 数据和模型

   GEPU：2001-01-03到2017-01-31的时间跨度，全球经济不确定指数由16个国家的EPU的加权平均
   数(权重即为GDP);
   COMEX gold price from Bloomberg;

   GARCH-MIDAS model with EPU;
   GARCH-MIDAS model with RV; 
   GARCH-MIDAS model with RV+EPU
   然后进行模型评估，样本外预测，并和GARCH(1,1)比较

#### GEPU与中国股市  

1. Forecasting performance of global economic policy uncertainty for volatility
   of Chinese stock market[@Yu2018]

   GEPU对上证综指波动率的影响研究；

   用GARCH-MIDAS模型来评估每月GEPU指数对每日的影响上证综合指数。我们的实证结果表
   明，GEPU对中国股市的波动性具有积极而显着的影响，这表明中国股市已逐渐融入全球
   经济。此外，与具有RV的GARCH（1,1）模型和具有RV的GARCH-MIDAS模型（由RMSE，
   RMAE，RMSD，RMAD损失函数和DMtest测得）相比，使用GEPU和RV（实际波动率）的
   GARCH-MIDAS模型生成的预测产生的误差要小得多。总的来说，我们的发现表明GEPU是中
   国股市长期波动性的附加驱动因素。

#### GEPU与原油

1. Which determinant is the most informative in forecasting crude oil market
   volatility: Fundamental, speculation, or uncertainty?[@Wei2017]

   将全球经济政策不确定性（GEPU）指数和一些国家经济政策不确定性（EPU）指数与传统
   的决定因素（例如全球石油需求，供应和投机活动）整合在一起。 我们的分析表明，
   EPU指数全面整合了其他决定因素中包含的信息。具体而言，GEPU指数和美国EPU指数对
   西德克萨斯中质原油的波动具有超强的预测能力。该发现凸显了EPU指标的重要性，这
   意味着它们是确定原油市场波动时要考虑的关键因素。

   - 石油价格受哪些因素影响

   但是，预测原油的波动是一项艰巨的任务，因为原油市场非常复杂，并且具有不确定的
   决定因素，例如全球石油供求，OPEC备用产能水平，金融危机和全国大选。一些研究者
   声称，油价变化在很大程度上取决于石油需求和供应，尤其是全球需求,Dées et al.,
   2007; Kilian, 2009; Muand Ye, 2011).；但是，其他研究认为，投机性因素起着关键
   作用 (Zhang, 2013; Hamilton and Wu, 2014;Kilian and Murphy, 2014; Juvenal and
   Petrella, 2015; Gogolin andKearney, 2016)
   
   Liu et al.解释了石油需求，供应和投机对实际石油价格的贡献，（Yin and Zhou，
   2016）指出了投机和经济基本面在推动油价波动中的作用。但是，正如Baker等人的开创
   性工作一样（2013年）,在衡量经济政策不确定性（EPU）时，值得一提的是，许多研究
   已经检验了EPU对股票市场的影响，并在预测股票市场收益时考虑了EPU指数。近年来，
   有关EPU对石油市场影响的文献越来越多（例如，Aloui等人，2016; Balcilar等人，
   2016; Yin，2016）。例如，Aloui等（2016年）认为，不确定性指数的变化可以识别直
   接驱动油价的供给方，总需求和特定于石油的需求冲击。因此，不确定性指数的增加
   （减少）可能对经济产生负面（正面）影响，从而降低（增加）原油的供求关系，进而
   导致油价波动。 Balcilar（2016年）也强调，EPU可以推动油价波动。

   我们推测，较高的EPU会同时导致石油消费者，生产者和投机者的期望出现严重分歧，从
   而影响原油的需求，供应或投机市场。因此，EPU可能会全面涉及各种诸如石油冲击，金
   融危机和政治事件之类的信息，这些信息极大地影响着石油市场并导致油价波动。但
   是，尚不清楚EPU是否是预测油价波动性中最有用的因素，哪个决定因素是最有力的仍有
   待解决。

   - 解决两点问题
      * 第一，EPU是否能够帮助预测原油波动率
      * 第二，在石油需求，供应，投机活动或新的EPU指数中，哪一个是对石油波动率预
        测最有帮助的。
   - 指标说明
      * 来自全球主要石油消费者和生产商的两个新发布的月度全球EPU（GEPU）指数和六
        个特定国家/地区的EPU指数。 两种GEPU只是权重不同，一种以GDP为权重，一种以
        购买力指数为权重(PPP).六个国家是三个主要石油需求国(美国、中国、日本)和三
        个石油提供国(英国、俄罗斯、加拿大)
      * 月度全球石油需求数据，供应量数据以及投机市场数据
      * 每日的WTI原油波动率数据(西德克萨斯中质（WTI）石油)
      * 全球石油需求指数是根据基利安和帕克（Kilian and Park）（2009）开发的干货
        运输价格指数构建的，用于衡量全球实际经济活动的指标。
      * 全球石油供应记录以全球原油产量为代表，可在美国能源信息署（EIA）的每月能源评
        论中找到。 
      * 使用EIA记录的OECD石油存量与美国石油存量之比来代表石油投机活动

   - 模型说明
      * 使用具有不同月度决定因素的GARCH-MIDAS模型对每日油价波动进行建模。 
      * 为了提供自变量的时变效应，还应用DMA组合方法，使一组自变量及其系数随时间变化。
      * 模型检测方面，使用强大的高级模型置信度集（MCS）检验评估模型的预测性能（Hansenet等，2011）。
      * 以8个EPU和3个宏观变量为自变量建立11个GARCH-MIDAS模型，然后通过MCS来发现预测波动率的最佳变量。
      * 三个DMA模型组合分别为:所有EPU,所有宏观变量，所有变量。

2. Uncertainty and oil volatility: New evidence[J]. Physica A: Statistical
   Mechanics and its Applications,2019,525[@Mei2019].
3. The forecasting power of EPU for crude oil return volatility[J]. Energy
    Reports,2019,5[@Ma2019].
    - 8个EPU中，看哪个EPU对石油收益波动率预测效果最佳(两个GEPU,进口国美国，欧
      洲，中国；输出国俄罗斯，墨西哥，加拿大)
    - 变量:8个EPU,1个CVX(Crude Oil Volatility Index)，一个原油数据
    - 原油数据用Brent crude oil prices(from Bloomberg database)
    - 模型:
      * 首先构建含有不同EPU的8个GARCH-MIDAS模型，EPU有不同滞后项
      * 然后构建同时还有EPU和CVX的8个GARCH-MIDAS模型，还有一个只含有CVX的模型，
        含有两个变量的模型和仅有CVX的模型做比较
      * 用MCS检验做模型比较

#### 宏观经济变量与美国股市

1. The importance of the macroeconomic variables in forecasting stock return
   variance: A GARCH‐MIDAS approach[@Asgharian2013]
   
   我们研究了一大批宏观经济变量，包括意外通货膨胀，定期溢价，人均劳动收入增长，
   违约溢价，失业率，短期利率和人均消费。我们调查具有经济变量的GARCH-MIDAS模型预
   测短期和长期波动率的能力。然后将这些模型的性能与作为基准的GARCH（1，1）模型进
   行比较。
   
   为了捕获包含在不同经济变量中的信息并调查它们的综合影响，我们进行了主成分分
   析。我们的结果表明，在GARCH-MIDAS模型中包含低频宏观经济信息可以提高模型的预测
   能力，尤其是对于长期方差分量。此外，以第一主成分增强的GARCH-MIDAS模型优于所有
   其他规范。
   
   在单个宏观经济变量中，当包含在MIDAS方程中时，短期利率和违约率表现优于其他变
   量。

   变量:
   选择许多对**美国标准普尔指数波动率**有重要影响的金融和宏观经济变量，有失业率，GDP
   增长率，违约率，短期利率，通货膨胀率等

   模型有:
   GARCH-MIDAS MODEL WITH RV;
   GARCH-MIDAS MODEL WITH RV+Xl+XV（Xl和Xv分别表示宏观经济变量的均值和波动率）;
   GARCH-MIDAS MODEL WITH Xl+XV

2. **STOCK MARKET VOLATILITY AND MACROECONOMIC FUNDAMENTALS   The Review of
   Economics and Statistics **  2013-07[@Engle2013].
   - 摘要:
     我们使用一类新的成分模型重新审视了股票市场的波动性与宏观经济活动之间的关
     系，该模型将短期与长期波动区分开。正如Schwert（1989）一样，我们研究了始于19
     世纪的长期总体股市波动的历史数据系列。我们以通胀和工业生产增长为驱动力的长
     期成分来制定模型，这些模型在针对四分之一水平的伪样本外预测中处于同等水平，
     而在更长时间内与传统时间序列波动性模型处于同等或优于同等水平视野。因此，将
     经济基本面纳入波动率模型可以带来长期预测。我们还发现，在每天的水平上，通货
     膨胀和工业生产增长占提前一天的波动预测的10％至35％。因此，即使在短期内，宏
     观经济基本面也发挥着重要作用。不幸的是，所有模型-纯粹是时间序列模型，以及受
     经济变量驱动的模型-都具有跨越整个样本的结构突破，这些样本跨越了大约一个半世
     纪的每日数据。因此，我们的分析还集中在子样本上，即第一次世界大战之前，大萧
     条时代和第二次世界大战之后（也用于检验所谓的“大温和”）。我们的主要发现在所
     有子样本中仍然有效。
   - 特点:
     将经济基本面并归到波动率模型中，可以进行长短期预测，计算经济基本面变量对波
     动率的贡献度。用通货膨胀和工业生产增长驱动的长期成分来制定模型，在一个季度
     的样本外预测时处于中等水平，在预测更长的区间时，效果与传统时间序列模型平等
     或更佳。
   - 模型:
      * 引入波动率的变量可以实现是波动率(一个周期)或者是宏观经济基本面变量
      * 对于样本有结构突变的情况，可能需要分时间段分析，也就是说不能有效捕捉结构突变。
      * 模型的长期波动部分，BETA权重具有很强的灵活性，可以描述权重较大的增加(减少)。
      * 当模型参数固定，可以比较不同时间段的GARCH-MIDAS,还可以设置变量的不同滞后
        阶数，不同滞后阶数的权重不同。
      * 长期波动部分为RV时，有固定窗口和滚动窗口两种
      * 长期波动部分为经济变量IP(PPI)时，有IP(PPI)水平和IP(PPI)波动率对STOCK波动率的影响3种
3. Two are better than one:volatility forecasting using multiplicative
   component GARCH-MIDAS models(2019)[@Conrad2020]
   - 是对所有乘积M-GARCH类模型的总结。
     GARCH-MIDAS模型将是我们乘积GARCH（M-GARCH）模型的主要示例; 
     Haas(2004)等人的Markov-Switching GARCH（MS-GARCH);
     Engle和Rangel（2008)的Spline-GARCH;
     Amado和Terâasvirta(2008)的乘性时变GARCH（MTV-GARCH）
   - 在样本外预测时，将GARCH-MIDAS与HAR(Corsi2009), the Realized
     GARCH(Hansen2012), the HEAVY（Shephard and Sheppard2010),以及MS-GARCH4种模
     型做比较.根据有或没有杠杆的共8个模型。
4. A Regime-Switching GARCH-MIDAS Approach to Modelling Stock Market Volatility
    - 导致波动的因素有四个：实际消费，消费者信心，房屋价格和价差
    - 研究对象:美国标准普尔指数
    - 结果:
      马尔可夫转换并没有提高GARCH-MIDAS的性能，在预测时甚至更差。这意味着在
      该GARCH-MIDAS设置中考虑的宏观经济变量已经包含了与区制变更相关的信息。
    - 展望:
      在考虑S＆P500指数时，500种个体股票的聚集减少了个体冲击的影响，因此宏
      观经济效应比单个股票可能存在的影响更为明显，还应探索波动过程变化的不同方
      法，例如，宏观经济变量的意义取决于经济状况可能是合理的，因此在经济低迷时
      期影响可能更大。当宏观经济基本面发生重大变化时，可以通过马尔可夫转换MIDAS
      组件或MIDAS组件的激活函数来探索这一点。

#### EPU与美国股市

1. The role of the political cycle in the relationship between economic policy
   uncertainty and the long-run volatility of industry-level stock returns in
   the United States[@Yu2018a]. 

   * 政治周期在美国经济政策不确定性与行业水平股票收益的长期波动之间的关系中的作用

#### 中美经济不确定性对汇率

1. Can economic policy uncertainty predict exchange rate volatility? New
   evidence from the GARCH-MIDAS model[J]. Finance Research
   Letters,2019[@Zhou2019].
   * 研究对象:中美经济政策的不确定性对汇率波动性的影响
   * 模型:GARCH-MIDAS与传统的GARCH类模型（GARCH,TGARCH,EGARCH,PGARCH）进行对比
   * 内容:the Sino-US EPU ratio对中国汇率波动率的影响以及the Sino-US EPU ratio如何预测汇率的波动性。
   * 细节:汇率从2005年开始发行，2016年，RMB加入SDR,成为继美元欧元之后占比第三的
     货币。汇率波动会影响对外贸易成本，增加国内外投资风险。
   * 创新:研究对象的选择有新意
   * 指标:
     - 汇率(2003-01-01到2018-09-28的日度数据)
     - 中美经济不确定性:the Sino-US EPU ratio(2003-01到2018-09的月度数据)=中国EPU/美国EPU
#### 其他
1. Forecasting stock price volatility: New evidence from the GARCH-MIDAS
   model[J]. International Journal of Forecasting,2020,36(2)[@Wang2020].
   - 对象:美国标准普尔指数
   - 模型:通过改变GARCH-MIDAS模型中短期成分和长期成分的模型设定，共构建三种模型
      * 标准的GARCH-MIDAS模型：残差项是正态分布，短期成分是GARCH(1,1),长期成分是
        包含已实现波动率滞后项的模型
      * 包含非对称效应的GARCH-MIDAS:短期成分中使用GJR(1,1)模型，长期成分用包含已
        实现的半方差量度，可以分别显示正收益和负收益的变化。
      * 含有极端效应的GARCH-MIDAS
      * 同时含有非对称效应和极端效应的GARCH-MIDAS
   - 摘要:
     文章介绍了非对称性和极端波动性影响的组合，以建立用于建模和预测股票波动性的
     GARCH-MIDAS模型的出色扩展。我们的样本结果清楚地证明了极端冲击对股票的波动性
     有重大影响，并且波动性在长期和短期内受不对称效应的影响要大于受极端波动效应
     的影响。 带有多个鲁棒性检查的样本外结果表明，我们提出的模型可以在预测波动率
     方面取得更好的性能。 此外，预测能力的提高更强烈地归因于短期波动性成分的不对
     称性和极端波动性效应的引入。
2. 极端波动下的股市波动率预测研究--基于非对称GARCH-MIDAS模型[D].西南交通大学,2019[@杨林2019].
   模型说明:对于短期成分用GJR-GARCH模型替换标准GARCH-MIDAS模型中的GARCH过程,
   长期成分则是把已实现波动率分解成已实现正方差和已实现负方差。此外,为了捕获市场
   中由极端事件引起的极端波动,本文对GARCH-MIDAS模型进行了进一步的改进,其中在短期
   成分中引入不同的门限变量,而在长期成分中的做法是把已实现波动率进一步分解。通过
   上面的改进本文得到了15种不同的GARCH-MIDAS模型。

### 国内文献

#### 中国EPU与不同股市

1. 中国经济政策不确定性与亚洲股市的动态关系——基于时变Copula模型的分析[@韩菲2018]
2. 经济不确定性是股市波动的因子吗?——基于GARCH-MIDAS模型的分析[J].中国管理科
   学,2018,26(12):1-11[@夏婷2018].
   * 经济不确定有两方面:宏观经济不确定性包括实体经济运行情况、消费情况、货币政
     策，经济政策不确定性用EPU指标
   * 将外生变量引入多元混频模型，分析短期波动率和长期波动率。
   * 研究对象为A股和B股
   * 模型:GARCH-MIDAS-RV,GARCH-MIDAS-RV+CEPU,GARCH-MIDAS-RV+AEPU,GARCH-MIDAS-RV+IP,
     GARCH-MIDAS-RV+INF,GARCH-MIDAS-RV+IR
3. 经济政策不确定性与我国股市波动率预测研究[J].管理科学学报,2018[@雷立坤2018].
   * 研究对象:Baker的经济政策不确定性 (economic policy uncertainty, EPU) 指数和
     我国股市代表性的股价指数——上证综指
   * 不同EPU滞后期的GARCH-MIDAS模型与采用同频数据的GARCH族模型做比较
4. 经济政策不确定性与我国股市的波动率预测[@余江2018]
   * 研究对象为沪深300指数
5. 中国经济政策不确定性对公司债波动的影响研究[J].金融与经济,2018[@张茂军2018].

6. 引入经济政策不确定性指标的沪深300指数已实现波动率建模研究[D].南京大学,2019[@杨涛2019].
   * 经济政策不确定性用陆尚勤和黄昀(2019)编制的日度和月度中国经济政策不确定性指
     数(China Economic Policy Uncertainty Index,CEPU指数)
   * GARCH-MIDAS-D(日度),GARCH-MIDAS-M(月度),GARCH-MIDAS

7. 我国股票市场波动与经济政策不确定性的关联性研究[D].吉林大学,2017[@王永莲2017].

8. 经济政策不确定性与股市波动关系研究[J].价值工程,2019,38(05):192-196[@石强2019a]
   - 从经济政策不确定性波动率和水平值两方面进行不同时期的GARCH-MIDAS模型构建

**总结** 关于EPU与中国金融市场的研究，研究对象多为股市，具体由上证综指，由
沪深300，同时涉及研究角度(水平值和波动率)和数据的不同(Baker或者黄昀)

#### 中国宏观经济与中国股市

1. 基于GARCH-MIDAS模型的宏观经济与股市波动关系[J].计算机工程与应
    用,2019,55(15):257-262+270[@石强2019].
2. 基于我国货币政策不确定性的股市波动长短期成分测度研究[J].金融发展研究,2017[@周德才2017].
   * 我国综合股价指数:选择上证综指 (SHZI) 、深证综指 (SZCI) 以及香港恒生中国企业
     指数 (HSCEI) 三个股票指数的日收益率, 使用BDFM模型测度得到股市贝叶斯动态公因
     子作为综合股价指数。
   * 货币政策不确定指标:基于货币供应量、利率、汇率、信贷四个货币政策变量, 使用HP
     滤波得到其不确定性成分, 构建金融状况指数 (FCI) 作为货币政策的代理变量
3. 债券市场收益率波动与风险测量研究——基于GARCH-MIDAS模型分析[J].价格理论与实
   践,2018(10):101-104.
   - 变量为利率、通货膨胀、经济增长、货币供给以及替代金融资产的价格
   - 从宏观金融变量的水平和波动率两个方面进行研究

#### 其他

1. 经济政策不确定性对我国物流指数波动率的影响[J].物流技术,2018[@胡杨2018].

## 基于宏观经济因素的金融市场关系研究

1. 沪铜期货与上证A股长短期波动与动态非对称相关性研究——基于宏观经济因素视角的混频
   数据分析[J].上海师范大学学报(哲学社会科学版),2019,48(04):113-124[@李佳2019].
   - 不涉及EPU
   - 研究对象:上海期货交易所沪铜期货和上证A股综合指数以及中国宏观经济景气指数
   - 模型:
      * 用GARCH-MIDAS考察中国宏观经济对商品期货市场和股票市场长短期价格波动的影响,
      * 用DCC-MIDAS模型(根据2008年金融危机这一历史事件划分样本区间)考察期货市场
        和股票市场长期相关性在金融危机前后存在的结构性变动。

___

2. Conrad et al.(2014)研究了石油和股票市场的相关性，并且检测是否石油波动率，股
     票波动率以及他们之间的相关性对于同一个宏观经济信息的反应

3. 经济政策不确定性如何影响金融市场间的流动性协同运动?——基于中国金融周期的视角
   [J].统计研究,2020,37(02):37-51[@张宗新2020].
   - 涉及EPU
   - 股债两市流动性的相关性(经济政策不确定性如何影响股债两市流动性自身的波动及市场
     间的联动,进一步考察这一影响在金融周期的不同阶段是否呈现非对称性)。
   - 模型:DCC-MIDAS，流动性测度
   - 创新点:
     * 现有对金融市场动态相关性的研究普遍集中于收益及其波动，作者从市场流动性联动的视角出发
     * 对DCC-GARCH-MIDAS模型引入经济不确定性和经济周期虚拟变量

___

1. 银行间债券市场与利率互换市场的联动性——基于DCC-MIDAS模型的实证[J].系统工
   程,2018,36(01):13-21[@张屹山2018].
   - 不涉及EPU
   - 大多数研究学者认为金融市场的波动一部分来源于宏观经济波动，还有一部分来源于
     随机的突发事件、日内交易及投资者情绪等，根据金融市场波动率的产生根源，可以
     将金融市场的波动进行成分分解。应用DCC-MIDAS模型，从长短期两个角度考察中国银
     行间债券市场与利率互换市场之间的联动性及宏观经济风险对两个市场波动性的影
     响。
   - 创新点：
     * 在DCC-MIDAS中引入宏观经济风险
     * 研究对象的创新:银行间债券市场与利率互换市场，大部分研究是关注股市.
   - 模型：DCC-MIDAS模型是DCC模型和GARCH-MIDAS模型的有机结合，不仅能够刻画每个市
     场的混频成分波动，还能分析多个市场间的波动率成分动态条件相关。
   - 对象:
     * 债券:银行间债券市场总指数的财富指数
     * 宏观经济变量季节性处理后的残差序列平方作为波动率来度量经济波动性。

**总结** 国内文献对金融市场相关性的研究中引入EPU的文献很少,宏观经济对股市的影响
中有水平值和波动率两方面

## 参考文献

[//]: # (\bibliography{Bibfile})


